### ISSUE TITLE
issues linked to multiple inheritance.

### ISSUE THREAD

**Issue by pvalvin** [PyMoDAQ/pymodaq_plugins_andor#4]
Dear Pymodaq team, dear Sebastien,

Last week, I wanted to implement the pymodaq-plugins-andor to drive an Andor system (Spectro Shamrock and CCD Newton).
So I cloned and installed the plugin available on Github.
After correcting the links to the dlls, I was able to start testing:
- the Shamrock drive plugin alone works
- the CCD-only plugin works
In order to benefit from the calibration features provided by the dll, I wanted to test and use the plugin that inherits from the 2 instruments, i.e. daq_1Dviewer_ShamrockCCD.
I couldn't make it work.

The first error is described by the following message:
> _File "c:\repo\pymodaq_plugins_andor\src\pymodaq_plugins_andor\daq_viewer_plugins\plugins_1D\daq_1Dviewer_ShamrockCCD.py", >line 42, in __init__
>    DAQ_Move_Shamrock.__init__(self, parent, params_state)
>
>  File "c:\repo\pymodaq_plugins_andor\src\pymodaq_plugins_andor\daq_move_plugins\daq_move_Shamrock.py", line 41, in __init__
>    super().__init__(parent, params_state)  # initialize base class with common attributes and methods
>    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "C:\repo\PyMoDAQ\src\pymodaq\control_modules\move_utility_classes.py", line 225, in __init__
>    self._title = parent.title
>                  ^^^^^^^^^^^^
>AttributeError: 'DAQ_Detector' object has no attribute 'title'
>
>2023-11-10 15:35:11,302 - pymodaq.pymodaq.daq_viewer.Det 00 - INFO - detector initialized: False
>2023-11-10 15:36:11,537 - pymodaq.dashboard - INFO - Preset file: C:\ProgramData\.pymodaq\preset_configs\CWPL.xml has been >loaded_

This problem is solved by adding 
> self.title=title 

to the DAQ_Detector object (added on line 1177 of daq_viewer.py).

But other errors appear, and they look more tricky to fix : we come across an error originating on line 228 of move_utility_classes:
> self._current_value = DatatActuator(self._title, data=np.zeros(...))
The error given as a result is :
> Data should be an non-empty list of non-empty numpy array.

Debugging under pycharm seems complex and we've decided to publish this issue. Could it be related to the switch to pymodaq-v4 ?

Thank you for your help,

Pierre Valvin - L2C Montpellier

**Comment by seb5g** [comment]
I'm on it

**Comment by seb5g** [comment]
hello,
I've cleaned the problems and it shouldbe working now.
I tested: 

- AndorCCD and AndorSCMOS 2D plugins
- Shamrock Move plugin
- ShamrockCCD 1D pluign
- ShamrockCCDComposition new 1D plugin

**Comment by seb5g** [comment]
solved by PR #5 and published 1.1.0 release

**Comment by pvalvin** [comment]
Thank you Sebastien. Great ! We will test it asap and let you know.

**Comment by pvalvin** [comment]
Hi Sebastien, We have just checked the new plugin and it works perfeclty ! Thank you so much for your work,
Best,
Pierre
